---
- hosts: ansible

  tasks:
  - name: create docker image
    command: docker build -t reggapp:latest .
    args:
      chdir: /opt/docker

  - name: create tag to push image into dockerhub
    command: docker tag reggapp:latest matich/regapp:latest

  - name: push docker image
    command: docker push matich/regapp:latest

